Update negation text to reflect current common practice in CKM
openEHR/specifications-RM pull request #27
Opened 2024-11-16 07:34 UTC by joostholslag

2024-11-16 16:49 UTC, freshehr commented on docs/data_types/master05-text_package.adoc
> +in the openEHR Reference Model; rather it's usually solved by specific 'exclusion' entry archetypes.
in the openEHR Reference Model. Negation statements are normally solved by specific 'exclusion' archetypes.

2024-11-16 16:50 UTC, freshehr requested changes
in the openEHR Reference Model. Negation statements are normally solved by specific 'exclusion' archetypes.

2024-11-18 15:02 UTC, joostholslag commented
Could you commit it?

2024-11-18 15:02 UTC, joostholslag commented
> in the openEHR Reference Model. Negation statements are normally solved by specific 'exclusion' archetypes.

Could you commit this change?

2025-11-12 06:36 UTC, joostholslag commented on docs/data_types/master05-text_package.adoc
> +in the openEHR Reference Model; rather it's usually solved by specific 'exclusion' entry archetypes.
Changed.

2025-11-12 07:59 UTC, freshehr approved these changes

2025-11-12 08:01 UTC, merged